// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace PullableViewExample
{
	public partial class PullUpContainerViewController : UIViewController
	{
		public PullUpContainerViewController (IntPtr handle) : base (handle)
		{
		}

		public void SetLabelText(string text) {
			SomeLabel.Text = text;
		}
	}
}
